token:
  expiration_time: 864000000
  secure: '{cipher}AYBNdGesoG2JlGeCZnYqrCpQvDyMj/ldV8mM+TVv/CYP7EtRg6qQF7Vfzbswz3jQ83NcaDbReA3ZVreNMYGlzcPHWUsSjrJ0EL+4DeoxtlFeRfbMzP/tF8TjNA6cqEu2VWnNLWtkFWPswWrHzMYbkyutXkq2aoVjEqrlAXTrwQy/l3FuR4YF4c8qHgE4U0wRT/Nt4aPH4fKsPhWJzdA1bmn/A+pgp/t5A8KY/+/Kd8BT2wiX9JbI3A31ZYpghVmkVdqbSJa6JoTxoTTlWOZPzzY6piu8v+mWhof3GlL2TNUZuVenkIQdSZ0oRUSVLw4sucOGtrDwOxP36zhTc1Fgb6LVHXHzq6gtHEtYs7h45E+tWcKPOe3FU5MWGo2LIHef4S+OshYF9xG6ETQXusuJQyL4sZNXtN7yWStaLSfAx3VWjc5nWam6UxEE3QWdj+sLqypHWJbqZj8NiIy0+YP8ggdYv++E4JwzeHdtyg6BzAO4avheIfbPt3cC49ZmPMsl+JeqAgvX6ED6SMfOwYf2hV70Q1Ebfp860n7jzP/GOcQfuu6vQYsITaIZheXpem4/hB4rVBCKfk/IArdRsrcX7uaU2rGN1QBFA5tw5J0swUHg1R0DOR2bQEYu12TWmvfHAlg='
#  secret: user_token_git_very-long-and-secure-hmac-secret-key-1234567890123456

gateway:
  ip: 172.18.0.1
